### ISSUE TITLE
Crash while opening reports view too quickly

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#966]
When loading a saved game, pressing F1 to open the reports view can lead to crash when done too quickly. For instance, the view might still be fading in, and the UI may not be fully initialized.

The crash happens during the `activate()` call due to `mActiveState` being `nullptr`:
```cpp
void GameState::onShowReports()
{
	mActiveState->deactivate();
	mActiveState = mMainReportsState.get();
	mActiveState->activate();
}
```

I believe this is getting called before `GameState::initialize()` has a chance to run. The `initialize()` method is the only place that sets `mMainReportsState` (`std::unique_ptr<MainReportsUiState>`).

----

Crash details:
> Thread 1 "ophd.exe" received signal SIGSEGV, Segmentation fault.
> Wrapper::activate (this=0x0) at OPHD/Constants/../States/Wrapper.h:33
> 33		void activate() { mIsActive = true; _activate(); }
> (gdb)  bt
> #0  Wrapper::activate() (this=0x0) at OPHD/Constants/../States/Wrapper.h:33
> #1  0x0000000000686700 in GameState::onShowReports() (this=0xed6330)
>     at OPHD/States/GameState.cpp:156
> #2  0x00000000005de0dd in NAS2D::DelegateX<void>::operator()() const (this=0xeda0a0)
>     at nas2d-core/NAS2D/Signal/Delegate.h:429
> #3  0x00000000005ddf6e in NAS2D::Signal<>::emit() const (this=0xeb9640)
>     at nas2d-core/NAS2D/Renderer/../Signal/Signal.h:43
> #4  0x00000000005ddee5 in NAS2D::Signal<>::operator()() const (this=0xeb9640)
>     at nas2d-core/NAS2D/Renderer/../Signal/Signal.h:44
> #5  0x00000000006bec30 in MapViewState::onKeyDown(NAS2D::EventHandler::KeyCode, NAS2D::EventHandler::KeyModifier, bool) (this=
>     0xeb1d10, key=NAS2D::EventHandler::KeyCode::KEY_F1, mod=NAS2D::EventHandler::KeyModifier::Num) at OPHD/States/MapViewState.cpp:365
> #6  0x00000000006ed699 in NAS2D::DelegateX<void, NAS2D::EventHandler::KeyCode, NAS2D::EventHandler::KeyModifier, bool>::operator()(NAS2D::EventHandler::KeyCode, NAS2D::EventHandler::KeyModifier, bool) const
>     (this=0xec5420, params=NAS2D::EventHandler::KeyCode::KEY_F1, params=NAS2D::EventHandler::KeyModifier::Num, params=false) at NAS2D/Signal/Delegate.h:429
> #7  0x00000000006ed53a in NAS2D::Signal<NAS2D::EventHandler::KeyCode, NAS2D::EventHandler::KeyModifier, bool>::emit(NAS2D::EventHandler::KeyCode, NAS2D::EventHandler::KeyModifier, bool) const
>     (this=0x9c2460, params=NAS2D::EventHandler::KeyCode::KEY_F1, params=NAS2D::EventHandler::KeyModifier::Num, params=false) at NAS2D/Signal/Signal.h:43
> #8  0x00000000006ebb85 in NAS2D::Signal<NAS2D::EventHandler::KeyCode, NAS2D::EventHandler::KeyModifier, bool>::operator()(NAS2D::EventHandler::KeyCode, NAS2D::EventHandler::KeyModifier, bool) const
>     (this=0x9c2460, params=NAS2D::EventHandler::KeyCode::KEY_F1, params=NAS2D::EventHandler::KeyModifier::Num, params=false) at NAS2D/Signal/Signal.h:44
> #9  0x00000000006eb0e7 in NAS2D::EventHandler::pump() (this=0x9c21c0)
>     at NAS2D/EventHandler.cpp:666
> #10 0x00000000006e71b4 in NAS2D::StateManager::update() (this=0x7fffffffd380)
>     at NAS2D/StateManager.cpp:87
> #11 0x0000000000664514 in main(int, char**) (argc=1, argv=0x7fffffffdd08)
>     at OPHD/main.cpp:159
>

**Comment by ldicker83** [comment]
Oooh, fun. I'll investigate this. May be able to prevent this by just not having the event handlers respond until the fading is done (if that's truly where the problem lies).

Thanks for the report!
